### ISSUE TITLE
Do not query item value, use 2-way data binding instead

### ISSUE THREAD

**Issue by DanCharousek** [sunil-sandhu/vue-todo#1]
First of all, great Article Sunil!

Anyway, back to the point. I don't think it's a good idea to showcase such comparison of JS frameworks using statement like this:

```
let input = document.querySelector('input');
```

I dare to say, that one of the most powerful things that JS frameworks like Vue, React, Angular and others have brought to the developer's experience is 2-way data binding. Which is extremely useful but also extremely hard to get used to especially if you come from word of jQuery where querying values from DOM is your daily bread. It takes some time and practice to wrap one's mind around this. Especially for people who are new to the frameworks this might look like this is normal thing to do and might confuse them in the future.

My suggestion is to use `v-model` directive for vue and the equivalent counterpart for react.

I am not a React dev, so I don't know the exact syntax, but I can create PR for vue to update it if you want.

Lemme know what you thing.

Cheers!

**Comment by sunil-sandhu** [comment]
Hi @DanCharousek - thank you for this, appreciate it :)

So I initially tried to write both the Vue app and the React app as similar as possible - so ended up avoiding the use of v-model in the Vue app as I wasn't aware of an equivalent option in React. However, I think the point you raise is actually a really important thing to talk about, because v-model is one of the best things about Vue. So by all means, feel free to make updates to the git repository for VueToDo and I'll endeavour to make updates to the article over the weekend 👍 

Thanks again Dan :)

**Comment by sunil-sandhu** [comment]
Hi again @DanCharousek. Just wanted to let you know that I have implemented the changes you have recommended. Many thanks for your input :)

**Comment by DanCharousek** [comment]
@sunil-sandhu Thank you for letting me know. I was about to submit a PR during the afternoon. Guess I gotta be faster next time :)

**Comment by sunil-sandhu** [comment]
Hi @DanCharousek, just to let you know, I've mentioned you in the article on Medium now. I've linked to your github account, but let me know if you would prefer a link to somewhere else instead (eg. personal website, twitter etc). Thanks

**Comment by DanCharousek** [comment]
Thank you @sunil-sandhu, I really appreciate that. I think that mentioning me is more than enough to ask for.

**Comment by DanCharousek** [comment]
Hi @sunil-sandhu I wasn't sure how to reach to you otherwise, so I write here. I've published an early version of my Firefox extension written in Vue. I thought you might be interested, so if you want, feel free to get in touch :slightly_smiling_face: Repo is [here](https://github.com/DanCharousek/tabby).

Cheers!
